version: "3"
services:
    webapi-gateway:
        image: ursaciucadrian/webapi-gateway:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Gateways/WebApi-Gateway/Dockerfile
        depends_on:
            - reservation-service-api
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7000:80

    auth-service-api:
        image: ursaciucadrian/auth-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Auth-Service/Medifii.AuthService.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7001:80

    pharmacy-service-api:
        image: ursaciucadrian/pharmacy-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Pharmacy-Service/Medifii.PharmacyService/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7002:80

    product-service-api:
        image: ursaciucadrian/product-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Product-Service/Medifii.ProductService/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7003:80

    reservation-service-api:
        image: ursaciucadrian/reservation-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Reservation-Service/Medifii.ReservationService.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7004:80

    request-service-api:
        image: ursaciucadrian/request-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Request-Service/Medifii.RequestService.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7005:80

    scraper-service-api:    
        image: ursaciucadrian/scraper-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Scraper-Service/Medifii.ScraperService.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7006:80

    search-service-api:
        image: ursaciucadrian/search-service-api:latest
        restart: always
        build:
            context: .
            dockerfile: Src/Microservices/Search-Service/Medifii.SearchService.Api/Dockerfile
        depends_on:
            - sqlserver
        environment:
            - ASPNETCORE_ENVIRONMENT=production
        ports:
            - 7007:80

    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        restart: always
        environment:
            SA_PASSWORD: "Pass123!"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433