apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-deployment
  namespace: medifii
spec:
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - name: scraper
          image: medifii/scraper-service:v1
          ports:
            - containerPort: 8080